package spire

import (
	"encoding/json"
	"fmt"
	"path/filepath"

	"github.com/hxndghxndg/k8s4r/pkg/plugin"
)

// Config SPIRE 插件配置
type Config struct {
	// SocketPath Workload API socket 路径
	// 默认: /run/spire/agent.sock
	SocketPath string `json:"socketPath" yaml:"socketPath"`

	// TrustDomain 信任域
	TrustDomain string `json:"trustDomain" yaml:"trustDomain"`

	// ServerAddr SPIRE Server 地址
	ServerAddr string `json:"serverAddr" yaml:"serverAddr"`
	// ServerAddress 保留作为别名（向后兼容）
	ServerAddress string `json:"serverAddress,omitempty" yaml:"serverAddress,omitempty"`

	// Binary 二进制配置（支持自动安装或指定路径）
	Binary plugin.BinaryConfig `json:"binary,omitempty" yaml:"binary,omitempty"`

	// DataDir SPIRE Agent 数据目录
	DataDir string `json:"dataDir" yaml:"dataDir"`

	// LogLevel 日志级别 (DEBUG, INFO, WARN, ERROR)
	LogLevel string `json:"logLevel" yaml:"logLevel"`

	// NodeAttestor 节点认证方式
	NodeAttestor NodeAttestorConfig `json:"nodeAttestor" yaml:"nodeAttestor"`

	// Keyring Linux Keyring 配置
	Keyring KeyringConfig `json:"keyring" yaml:"keyring"`

	// JoinToken 如果使用 join_token 认证，这里指定 token
	JoinToken string `json:"joinToken,omitempty" yaml:"joinToken,omitempty"`

	// UseKeyring 是否使用 Keyring（简化配置）
	UseKeyring bool `json:"useKeyring,omitempty" yaml:"useKeyring,omitempty"`
}

// NodeAttestorConfig 节点认证配置
type NodeAttestorConfig struct {
	// Type 认证类型: join_token, x509pop, aws_iid, gcp_iit, azure_msi 等
	Type string `json:"type" yaml:"type"`

	// Config 认证器特定配置（JSON）
	Config json.RawMessage `json:"config,omitempty" yaml:"config,omitempty"`
}

// KeyringConfig Linux Keyring 配置
type KeyringConfig struct {
	// Enabled 是否启用 Linux Keyring 保护私钥
	Enabled bool `json:"enabled" yaml:"enabled"`

	// Type Keyring 类型: session, user, process
	// 推荐使用 session（每个登录会话独立）
	Type string `json:"type" yaml:"type"`
}

// Validate 验证配置
func (c *Config) Validate() error {
	// TrustDomain 必填
	if c.TrustDomain == "" {
		return fmt.Errorf("trustDomain is required")
	}

	// SocketPath 必填
	if c.SocketPath == "" {
		return fmt.Errorf("socketPath is required")
	}

	// ServerAddr 必填（向后兼容 ServerAddress）
	if c.ServerAddr == "" && c.ServerAddress == "" {
		return fmt.Errorf("serverAddr is required")
	}
	// 如果只设置了 ServerAddress，复制到 ServerAddr
	if c.ServerAddr == "" {
		c.ServerAddr = c.ServerAddress
	}

	if c.DataDir == "" {
		return fmt.Errorf("dataDir is required")
	}

	if c.LogLevel == "" {
		c.LogLevel = "INFO"
	}

	// 节点认证配置（可选，因为可能从环境变量读取）
	if c.NodeAttestor.Type == "" {
		c.NodeAttestor.Type = "join_token" // 默认使用 join_token
	}

	// 处理 useKeyring 简化配置
	if c.UseKeyring {
		c.Keyring.Enabled = true
		if c.Keyring.Type == "" {
			c.Keyring.Type = "session"
		}
	}

	// 验证 keyring 配置
	if c.Keyring.Enabled {
		if c.Keyring.Type == "" {
			c.Keyring.Type = "session" // 默认使用 session keyring
		}
	}

	return nil
}

// ToAgentConfig 转换为 SPIRE Agent 配置文件内容
// isFirstStart: 是否是首次启动（true=使用join_token，false=使用已保存的SVID）
func (c *Config) ToAgentConfig(isFirstStart bool) string {
	serverAddr := c.ServerAddr
	if serverAddr == "" {
		serverAddr = c.ServerAddress
	}

	// 解析服务器地址（提取主机和端口）
	serverHost := serverAddr
	serverPort := "8081"
	if idx := len(serverAddr) - 1; idx >= 0 {
		for i := len(serverAddr) - 1; i >= 0; i-- {
			if serverAddr[i] == ':' {
				serverHost = serverAddr[:i]
				serverPort = serverAddr[i+1:]
				break
			}
		}
	}

	// 转换所有路径为绝对路径
	absDataDir, _ := filepath.Abs(c.DataDir)
	absSocketPath, _ := filepath.Abs(c.SocketPath)
	absKeysDir := filepath.Join(absDataDir, "data", "keys")

	// 生成 SPIRE Agent 配置文件（HCL 格式，使用绝对路径）
	config := fmt.Sprintf(`# SPIRE Agent Configuration
# Generated by k8s4r

agent {
    data_dir = "%s"
    log_level = "%s"
    server_address = "%s"
    server_port = "%s"
    socket_path = "%s"
    trust_domain = "%s"
    insecure_bootstrap = true
}

plugins {
`, absDataDir, c.LogLevel, serverHost, serverPort, absSocketPath, c.TrustDomain)

	// 只在首次启动时添加 NodeAttestor 配置（join_token）
	if isFirstStart {
		config += fmt.Sprintf(`    NodeAttestor "%s" {
`, c.NodeAttestor.Type)

		// 添加 NodeAttestor 特定配置
		if c.NodeAttestor.Type == "join_token" {
			// join_token plugin 不需要配置，token 通过命令行环境变量传递
			config += `        plugin_data {
        }
`
		} else if len(c.NodeAttestor.Config) > 0 {
			config += fmt.Sprintf(`        plugin_data = %s
`, string(c.NodeAttestor.Config))
		}

		config += `    }

`
	} else {
		// 非首次启动，不需要 NodeAttestor（会使用 DataDir 中保存的 SVID）
		config += `    # Using existing SVID from data_dir (no NodeAttestor needed)

`
	}

	// KeyManager 使用绝对路径
	config += fmt.Sprintf(`    KeyManager "disk" {
        plugin_data {
            directory = "%s"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {
        }
    }
}
`, absKeysDir)

	return config
}
