---
apiVersion: robot.k8s4r.io/v1alpha1
kind: Job
metadata:
  name: job-with-spire-envoy
  namespace: default
spec:
  type: service
  datacenters:
    - dc1
  taskGroups:
    - name: demo-group
      count: 1
      
      # InitTasks 按顺序执行，用于启动 SPIRE Agent 和 Envoy 代理
      initTasks:
        # 1. 启动 SPIRE Agent (守护进程)
        - name: spire-agent
          driver: exec
          daemon: true  # 守护进程模式，启动后不等待完成
          config:
            execConfig:
              command: /usr/local/bin/spire-agent
              args:
                - run
                - -config
                - /local/spire-agent.conf
          env:
            SPIRE_AGENT_TRUST_DOMAIN: "example.org"
          templates:
            # 生成 SPIRE Agent 配置文件
            - destPath: /local/spire-agent.conf
              embeddedTmpl: |
                agent {
                  data_dir = "/tmp/spire-agent"
                  log_level = "DEBUG"
                  server_address = "spire-server.default.svc.cluster.local"
                  server_port = "8081"
                  socket_path = "/run/spire/sockets/agent.sock"
                  trust_domain = "example.org"
                  
                  # Join token for workload attestation
                  join_token = "test-join-token-123"
                }
                
                plugins {
                  NodeAttestor "join_token" {
                    plugin_data {
                    }
                  }
                  
                  KeyManager "disk" {
                    plugin_data {
                      directory = "/tmp/spire-agent/keys"
                    }
                  }
                  
                  WorkloadAttestor "unix" {
                    plugin_data {
                    }
                  }
                }
        
        # 2. 等待 SPIRE Agent 准备就绪
        - name: wait-spire-ready
          driver: exec
          daemon: false  # 非守护进程，等待完成
          config:
            execConfig:
              command: /bin/bash
              args:
                - -c
                - |
                  echo "Waiting for SPIRE Agent socket..."
                  for i in {1..30}; do
                    if [ -S /run/spire/sockets/agent.sock ]; then
                      echo "SPIRE Agent is ready!"
                      exit 0
                    fi
                    echo "Attempt $i: SPIRE Agent not ready, waiting..."
                    sleep 2
                  done
                  echo "SPIRE Agent failed to start within timeout"
                  exit 1
        
        # 3. 启动 Envoy 代理 (守护进程)
        - name: envoy-proxy
          driver: exec
          daemon: true  # 守护进程模式
          config:
            execConfig:
              command: /usr/local/bin/envoy
              args:
                - -c
                - /local/envoy-config.yaml
                - --log-level
                - debug
          env:
            ENVOY_ADMIN_PORT: "9901"
          templates:
            # Envoy 配置将由 task_executor 自动生成
            # 这里只是示例，实际会被 envoy_config.go 生成的配置覆盖
            - destPath: /local/envoy-config.yaml
              embeddedTmpl: |
                # This will be auto-generated by task_executor
                admin:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9901
      
      tasks:
        - name: web-server
          driver: exec
          config:
            execConfig:
              command: python3
              args:
                - -m
                - http.server
                - "8080"
                - --bind
                - "127.0.0.1"
          
          env:
            APP_NAME: "demo-web-server"
            LOG_LEVEL: "info"
          
          # 网络代理配置
          network:
            enabled: true
            type: envoy
            spiffe:
              trustDomain: "example.org"
              agentSocketPath: "/run/spire/sockets/agent.sock"
            
            # 上游服务配置
            upstreams:
              - name: database
                localPort: 5432
                upstream: "postgres.default.svc.cluster.local:5432"
                protocol: tcp
                tls: true
              
              - name: api-service
                localPort: 8081
                upstream: "api.default.svc.cluster.local:443"
                protocol: http
                tls: true
          
          resources:
            cpu: "500m"
            memory: "512Mi"
          
          # 服务定义（用于服务发现和健康检查）
          services:
            - name: web
              portLabel: http
              tags:
                - web
                - demo
              checks:
                - name: alive
                  type: http
                  path: /
                  interval: 10s
                  timeout: 2s
