# 使用 raw_exec driver 运行脚本的 Task 示例
apiVersion: robot.k8s4r.io/v1alpha1
kind: Task
metadata:
  name: data-collector
  namespace: default
spec:
  # 任务驱动类型：raw_exec（无隔离执行，直接在主机上运行）
  driver: raw_exec
  
  # Driver 配置
  config:
    # 执行的脚本或命令
    command: "/bin/bash"
    
    # 脚本参数
    args:
      - "-c"
      - |
        #!/bin/bash
        # 数据收集脚本
        while true; do
          # 收集传感器数据
          python3 /opt/robot/scripts/collect_sensors.py
          
          # 上传到云端
          rsync -avz /var/robot/data/ robot-cloud:/storage/
          
          # 等待下一轮
          sleep 60
        done
    
    # 环境变量
    env:
      PYTHONPATH: "/opt/robot/lib"
      DATA_DIR: "/var/robot/data"
  
  # 资源需求（raw_exec 通常需要更谨慎的资源管理）
  resources:
    cpu: 200
    memoryMB: 512
    diskMB: 2048
  
  # 制品下载
  artifacts:
    - source: "https://storage.example.com/scripts/collect_sensors.py"
      destination: "/opt/robot/scripts"
      mode: "file"
  
  # 约束条件
  constraints:
    - attribute: "${attr.kernel.name}"
      operator: "="
      value: "linux"
  
  # 重启策略
  restartPolicy:
    attempts: 10
    interval: "1m"
    delay: "5s"
    mode: "delay"
  
  # 日志配置
  logs:
    maxFiles: 5
    maxFileSizeMB: 10
