// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: api/grpc/robot_manager.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskGroupCommand_CommandType int32

const (
	TaskGroupCommand_CREATE_TASKGROUP TaskGroupCommand_CommandType = 0 // 创建任务组
	TaskGroupCommand_DELETE_TASKGROUP TaskGroupCommand_CommandType = 1 // 删除任务组
	TaskGroupCommand_KEEPALIVE        TaskGroupCommand_CommandType = 2 // 保持连接
)

// Enum value maps for TaskGroupCommand_CommandType.
var (
	TaskGroupCommand_CommandType_name = map[int32]string{
		0: "CREATE_TASKGROUP",
		1: "DELETE_TASKGROUP",
		2: "KEEPALIVE",
	}
	TaskGroupCommand_CommandType_value = map[string]int32{
		"CREATE_TASKGROUP": 0,
		"DELETE_TASKGROUP": 1,
		"KEEPALIVE":        2,
	}
)

func (x TaskGroupCommand_CommandType) Enum() *TaskGroupCommand_CommandType {
	p := new(TaskGroupCommand_CommandType)
	*p = x
	return p
}

func (x TaskGroupCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskGroupCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_robot_manager_proto_enumTypes[0].Descriptor()
}

func (TaskGroupCommand_CommandType) Type() protoreflect.EnumType {
	return &file_api_grpc_robot_manager_proto_enumTypes[0]
}

func (x TaskGroupCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskGroupCommand_CommandType.Descriptor instead.
func (TaskGroupCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{6, 0}
}

type TaskGroupEvent_EventType int32

const (
	TaskGroupEvent_ACK       TaskGroupEvent_EventType = 0 // 确认收到指令
	TaskGroupEvent_PUBLISHED TaskGroupEvent_EventType = 1 // 已发布到 MQTT
	TaskGroupEvent_ERROR     TaskGroupEvent_EventType = 2 // 处理失败
	TaskGroupEvent_KEEPALIVE TaskGroupEvent_EventType = 3 // 保持连接
)

// Enum value maps for TaskGroupEvent_EventType.
var (
	TaskGroupEvent_EventType_name = map[int32]string{
		0: "ACK",
		1: "PUBLISHED",
		2: "ERROR",
		3: "KEEPALIVE",
	}
	TaskGroupEvent_EventType_value = map[string]int32{
		"ACK":       0,
		"PUBLISHED": 1,
		"ERROR":     2,
		"KEEPALIVE": 3,
	}
)

func (x TaskGroupEvent_EventType) Enum() *TaskGroupEvent_EventType {
	p := new(TaskGroupEvent_EventType)
	*p = x
	return p
}

func (x TaskGroupEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskGroupEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_robot_manager_proto_enumTypes[1].Descriptor()
}

func (TaskGroupEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_grpc_robot_manager_proto_enumTypes[1]
}

func (x TaskGroupEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskGroupEvent_EventType.Descriptor instead.
func (TaskGroupEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{7, 0}
}

type RegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RobotId        string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeviceInfo     *DeviceInfo            `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`               // 简化的设备信息
	DeviceInfoJson string                 `protobuf:"bytes,4,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"` // 完整的设备信息（JSON格式）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RegistrationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegistrationRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *RegistrationRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RobotId        string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeviceInfo     *DeviceInfo            `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`               // 简化的设备信息
	DeviceInfoJson string                 `protobuf:"bytes,4,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"` // 完整的设备信息（JSON格式）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUid       string                 `protobuf:"bytes,1,opt,name=task_uid,json=taskUid,proto3" json:"task_uid,omitempty"`
	RobotName     string                 `protobuf:"bytes,2,opt,name=robot_name,json=robotName,proto3" json:"robot_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // pending, running, completed, failed, dead
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Event         string                 `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`                           // Assigned, Downloading, Starting, Started, Completed, Failed
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{4}
}

func (x *TaskStatusRequest) GetTaskUid() string {
	if x != nil {
		return x.TaskUid
	}
	return ""
}

func (x *TaskStatusRequest) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *TaskStatusRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskStatusRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskStatusRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TaskStatusRequest) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TaskGroupCommand Manager → Server 的指令
type TaskGroupCommand struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          TaskGroupCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.TaskGroupCommand_CommandType" json:"type,omitempty"`
	TaskgroupJson string                       `protobuf:"bytes,2,opt,name=taskgroup_json,json=taskgroupJson,proto3" json:"taskgroup_json,omitempty"` // 完整的 TaskGroup JSON（包含所有字段）
	TaskgroupUid  string                       `protobuf:"bytes,3,opt,name=taskgroup_uid,json=taskgroupUid,proto3" json:"taskgroup_uid,omitempty"`    // TaskGroup UID
	RobotName     string                       `protobuf:"bytes,4,opt,name=robot_name,json=robotName,proto3" json:"robot_name,omitempty"`             // 目标机器人名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskGroupCommand) Reset() {
	*x = TaskGroupCommand{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskGroupCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskGroupCommand) ProtoMessage() {}

func (x *TaskGroupCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskGroupCommand.ProtoReflect.Descriptor instead.
func (*TaskGroupCommand) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{6}
}

func (x *TaskGroupCommand) GetType() TaskGroupCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return TaskGroupCommand_CREATE_TASKGROUP
}

func (x *TaskGroupCommand) GetTaskgroupJson() string {
	if x != nil {
		return x.TaskgroupJson
	}
	return ""
}

func (x *TaskGroupCommand) GetTaskgroupUid() string {
	if x != nil {
		return x.TaskgroupUid
	}
	return ""
}

func (x *TaskGroupCommand) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

// TaskGroupEvent Server → Manager 的事件（确认收到）
type TaskGroupEvent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          TaskGroupEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.TaskGroupEvent_EventType" json:"type,omitempty"`
	TaskgroupUid  string                   `protobuf:"bytes,2,opt,name=taskgroup_uid,json=taskgroupUid,proto3" json:"taskgroup_uid,omitempty"` // 任务组 UID
	RobotName     string                   `protobuf:"bytes,3,opt,name=robot_name,json=robotName,proto3" json:"robot_name,omitempty"`          // 机器人名称
	Message       string                   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskGroupEvent) Reset() {
	*x = TaskGroupEvent{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskGroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskGroupEvent) ProtoMessage() {}

func (x *TaskGroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskGroupEvent.ProtoReflect.Descriptor instead.
func (*TaskGroupEvent) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{7}
}

func (x *TaskGroupEvent) GetType() TaskGroupEvent_EventType {
	if x != nil {
		return x.Type
	}
	return TaskGroupEvent_ACK
}

func (x *TaskGroupEvent) GetTaskgroupUid() string {
	if x != nil {
		return x.TaskgroupUid
	}
	return ""
}

func (x *TaskGroupEvent) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *TaskGroupEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	NumCpus       int32                  `protobuf:"varint,4,opt,name=num_cpus,json=numCpus,proto3" json:"num_cpus,omitempty"`
	TotalMemory   int64                  `protobuf:"varint,5,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	KernelVersion string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetNumCpus() int32 {
	if x != nil {
		return x.NumCpus
	}
	return 0
}

func (x *DeviceInfo) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *DeviceInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *DeviceInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_api_grpc_robot_manager_proto protoreflect.FileDescriptor

const file_api_grpc_robot_manager_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/robot_manager.proto\x12\x04grpc\"\xa3\x01\n" +
	"\x13RegistrationRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x121\n" +
	"\vdevice_info\x18\x03 \x01(\v2\x10.grpc.DeviceInfoR\n" +
	"deviceInfo\x12(\n" +
	"\x10device_info_json\x18\x04 \x01(\tR\x0edeviceInfoJson\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x121\n" +
	"\vdevice_info\x18\x03 \x01(\v2\x10.grpc.DeviceInfoR\n" +
	"deviceInfo\x12(\n" +
	"\x10device_info_json\x18\x04 \x01(\tR\x0edeviceInfoJson\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcf\x01\n" +
	"\x11TaskStatusRequest\x12\x19\n" +
	"\btask_uid\x18\x01 \x01(\tR\ataskUid\x12\x1d\n" +
	"\n" +
	"robot_name\x18\x02 \x01(\tR\trobotName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05event\x18\x06 \x01(\tR\x05event\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"H\n" +
	"\x12TaskStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xff\x01\n" +
	"\x10TaskGroupCommand\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".grpc.TaskGroupCommand.CommandTypeR\x04type\x12%\n" +
	"\x0etaskgroup_json\x18\x02 \x01(\tR\rtaskgroupJson\x12#\n" +
	"\rtaskgroup_uid\x18\x03 \x01(\tR\ftaskgroupUid\x12\x1d\n" +
	"\n" +
	"robot_name\x18\x04 \x01(\tR\trobotName\"H\n" +
	"\vCommandType\x12\x14\n" +
	"\x10CREATE_TASKGROUP\x10\x00\x12\x14\n" +
	"\x10DELETE_TASKGROUP\x10\x01\x12\r\n" +
	"\tKEEPALIVE\x10\x02\"\xe1\x01\n" +
	"\x0eTaskGroupEvent\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.grpc.TaskGroupEvent.EventTypeR\x04type\x12#\n" +
	"\rtaskgroup_uid\x18\x02 \x01(\tR\ftaskgroupUid\x12\x1d\n" +
	"\n" +
	"robot_name\x18\x03 \x01(\tR\trobotName\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"=\n" +
	"\tEventType\x12\a\n" +
	"\x03ACK\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\r\n" +
	"\tKEEPALIVE\x10\x03\"\xa2\x02\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x19\n" +
	"\bnum_cpus\x18\x04 \x01(\x05R\anumCpus\x12!\n" +
	"\ftotal_memory\x18\x05 \x01(\x03R\vtotalMemory\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x124\n" +
	"\x06labels\x18\a \x03(\v2\x1c.grpc.DeviceInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb6\x02\n" +
	"\fRobotManager\x12P\n" +
	"\x17ReportRobotRegistration\x12\x19.grpc.RegistrationRequest\x1a\x1a.grpc.RegistrationResponse\x12G\n" +
	"\x14ReportRobotHeartbeat\x12\x16.grpc.HeartbeatRequest\x1a\x17.grpc.HeartbeatResponse\x12E\n" +
	"\x10ReportTaskStatus\x12\x17.grpc.TaskStatusRequest\x1a\x18.grpc.TaskStatusResponse\x12D\n" +
	"\x10StreamTaskGroups\x12\x14.grpc.TaskGroupEvent\x1a\x16.grpc.TaskGroupCommand(\x010\x01B&Z$github.com/hxndghxndg/k8s4r/api/grpcb\x06proto3"

var (
	file_api_grpc_robot_manager_proto_rawDescOnce sync.Once
	file_api_grpc_robot_manager_proto_rawDescData []byte
)

func file_api_grpc_robot_manager_proto_rawDescGZIP() []byte {
	file_api_grpc_robot_manager_proto_rawDescOnce.Do(func() {
		file_api_grpc_robot_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_robot_manager_proto_rawDesc), len(file_api_grpc_robot_manager_proto_rawDesc)))
	})
	return file_api_grpc_robot_manager_proto_rawDescData
}

var file_api_grpc_robot_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_grpc_robot_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_grpc_robot_manager_proto_goTypes = []any{
	(TaskGroupCommand_CommandType)(0), // 0: grpc.TaskGroupCommand.CommandType
	(TaskGroupEvent_EventType)(0),     // 1: grpc.TaskGroupEvent.EventType
	(*RegistrationRequest)(nil),       // 2: grpc.RegistrationRequest
	(*RegistrationResponse)(nil),      // 3: grpc.RegistrationResponse
	(*HeartbeatRequest)(nil),          // 4: grpc.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 5: grpc.HeartbeatResponse
	(*TaskStatusRequest)(nil),         // 6: grpc.TaskStatusRequest
	(*TaskStatusResponse)(nil),        // 7: grpc.TaskStatusResponse
	(*TaskGroupCommand)(nil),          // 8: grpc.TaskGroupCommand
	(*TaskGroupEvent)(nil),            // 9: grpc.TaskGroupEvent
	(*DeviceInfo)(nil),                // 10: grpc.DeviceInfo
	nil,                               // 11: grpc.DeviceInfo.LabelsEntry
}
var file_api_grpc_robot_manager_proto_depIdxs = []int32{
	10, // 0: grpc.RegistrationRequest.device_info:type_name -> grpc.DeviceInfo
	10, // 1: grpc.HeartbeatRequest.device_info:type_name -> grpc.DeviceInfo
	0,  // 2: grpc.TaskGroupCommand.type:type_name -> grpc.TaskGroupCommand.CommandType
	1,  // 3: grpc.TaskGroupEvent.type:type_name -> grpc.TaskGroupEvent.EventType
	11, // 4: grpc.DeviceInfo.labels:type_name -> grpc.DeviceInfo.LabelsEntry
	2,  // 5: grpc.RobotManager.ReportRobotRegistration:input_type -> grpc.RegistrationRequest
	4,  // 6: grpc.RobotManager.ReportRobotHeartbeat:input_type -> grpc.HeartbeatRequest
	6,  // 7: grpc.RobotManager.ReportTaskStatus:input_type -> grpc.TaskStatusRequest
	9,  // 8: grpc.RobotManager.StreamTaskGroups:input_type -> grpc.TaskGroupEvent
	3,  // 9: grpc.RobotManager.ReportRobotRegistration:output_type -> grpc.RegistrationResponse
	5,  // 10: grpc.RobotManager.ReportRobotHeartbeat:output_type -> grpc.HeartbeatResponse
	7,  // 11: grpc.RobotManager.ReportTaskStatus:output_type -> grpc.TaskStatusResponse
	8,  // 12: grpc.RobotManager.StreamTaskGroups:output_type -> grpc.TaskGroupCommand
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_grpc_robot_manager_proto_init() }
func file_api_grpc_robot_manager_proto_init() {
	if File_api_grpc_robot_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_robot_manager_proto_rawDesc), len(file_api_grpc_robot_manager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_robot_manager_proto_goTypes,
		DependencyIndexes: file_api_grpc_robot_manager_proto_depIdxs,
		EnumInfos:         file_api_grpc_robot_manager_proto_enumTypes,
		MessageInfos:      file_api_grpc_robot_manager_proto_msgTypes,
	}.Build()
	File_api_grpc_robot_manager_proto = out.File
	file_api_grpc_robot_manager_proto_goTypes = nil
	file_api_grpc_robot_manager_proto_depIdxs = nil
}
