// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: api/grpc/robot_manager.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RobotManager_ReportRobotRegistration_FullMethodName = "/grpc.RobotManager/ReportRobotRegistration"
	RobotManager_ReportRobotHeartbeat_FullMethodName    = "/grpc.RobotManager/ReportRobotHeartbeat"
	RobotManager_ReportTaskStatus_FullMethodName        = "/grpc.RobotManager/ReportTaskStatus"
	RobotManager_StreamTasks_FullMethodName             = "/grpc.RobotManager/StreamTasks"
)

// RobotManagerClient is the client API for RobotManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RobotManager 服务定义
// ========== 双向通信架构 ==========
// Server → Manager: 上报注册、心跳、任务状态
// Manager → Server: 推送任务创建、任务删除
type RobotManagerClient interface {
	// 单向 RPC：Server 通知 Manager 有 Robot 注册
	ReportRobotRegistration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
	// 单向 RPC：Server 通知 Manager 收到心跳
	ReportRobotHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// 单向 RPC：Server 通知 Manager 任务状态变化
	ReportTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	// ==========  双向流：Manager 推送任务给 Server ==========
	// Manager 监听 K8s Task 变化，通过此流推送给 Server
	// Server 将任务转发到 MQTT
	StreamTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskEvent, TaskCommand], error)
}

type robotManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotManagerClient(cc grpc.ClientConnInterface) RobotManagerClient {
	return &robotManagerClient{cc}
}

func (c *robotManagerClient) ReportRobotRegistration(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, RobotManager_ReportRobotRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotManagerClient) ReportRobotHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, RobotManager_ReportRobotHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotManagerClient) ReportTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, RobotManager_ReportTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotManagerClient) StreamTasks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskEvent, TaskCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RobotManager_ServiceDesc.Streams[0], RobotManager_StreamTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskEvent, TaskCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotManager_StreamTasksClient = grpc.BidiStreamingClient[TaskEvent, TaskCommand]

// RobotManagerServer is the server API for RobotManager service.
// All implementations must embed UnimplementedRobotManagerServer
// for forward compatibility.
//
// RobotManager 服务定义
// ========== 双向通信架构 ==========
// Server → Manager: 上报注册、心跳、任务状态
// Manager → Server: 推送任务创建、任务删除
type RobotManagerServer interface {
	// 单向 RPC：Server 通知 Manager 有 Robot 注册
	ReportRobotRegistration(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	// 单向 RPC：Server 通知 Manager 收到心跳
	ReportRobotHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// 单向 RPC：Server 通知 Manager 任务状态变化
	ReportTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	// ==========  双向流：Manager 推送任务给 Server ==========
	// Manager 监听 K8s Task 变化，通过此流推送给 Server
	// Server 将任务转发到 MQTT
	StreamTasks(grpc.BidiStreamingServer[TaskEvent, TaskCommand]) error
	mustEmbedUnimplementedRobotManagerServer()
}

// UnimplementedRobotManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobotManagerServer struct{}

func (UnimplementedRobotManagerServer) ReportRobotRegistration(context.Context, *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRobotRegistration not implemented")
}
func (UnimplementedRobotManagerServer) ReportRobotHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportRobotHeartbeat not implemented")
}
func (UnimplementedRobotManagerServer) ReportTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskStatus not implemented")
}
func (UnimplementedRobotManagerServer) StreamTasks(grpc.BidiStreamingServer[TaskEvent, TaskCommand]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTasks not implemented")
}
func (UnimplementedRobotManagerServer) mustEmbedUnimplementedRobotManagerServer() {}
func (UnimplementedRobotManagerServer) testEmbeddedByValue()                      {}

// UnsafeRobotManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobotManagerServer will
// result in compilation errors.
type UnsafeRobotManagerServer interface {
	mustEmbedUnimplementedRobotManagerServer()
}

func RegisterRobotManagerServer(s grpc.ServiceRegistrar, srv RobotManagerServer) {
	// If the following call pancis, it indicates UnimplementedRobotManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RobotManager_ServiceDesc, srv)
}

func _RobotManager_ReportRobotRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotManagerServer).ReportRobotRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotManager_ReportRobotRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotManagerServer).ReportRobotRegistration(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotManager_ReportRobotHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotManagerServer).ReportRobotHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotManager_ReportRobotHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotManagerServer).ReportRobotHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotManager_ReportTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotManagerServer).ReportTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RobotManager_ReportTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotManagerServer).ReportTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotManager_StreamTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RobotManagerServer).StreamTasks(&grpc.GenericServerStream[TaskEvent, TaskCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RobotManager_StreamTasksServer = grpc.BidiStreamingServer[TaskEvent, TaskCommand]

// RobotManager_ServiceDesc is the grpc.ServiceDesc for RobotManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RobotManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.RobotManager",
	HandlerType: (*RobotManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportRobotRegistration",
			Handler:    _RobotManager_ReportRobotRegistration_Handler,
		},
		{
			MethodName: "ReportRobotHeartbeat",
			Handler:    _RobotManager_ReportRobotHeartbeat_Handler,
		},
		{
			MethodName: "ReportTaskStatus",
			Handler:    _RobotManager_ReportTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTasks",
			Handler:       _RobotManager_StreamTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/grpc/robot_manager.proto",
}
