// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/grpc/robot_manager.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskCommand_CommandType int32

const (
	TaskCommand_CREATE_TASK TaskCommand_CommandType = 0 // 创建任务
	TaskCommand_DELETE_TASK TaskCommand_CommandType = 1 // 删除任务
	TaskCommand_KEEPALIVE   TaskCommand_CommandType = 2 // 保持连接
)

// Enum value maps for TaskCommand_CommandType.
var (
	TaskCommand_CommandType_name = map[int32]string{
		0: "CREATE_TASK",
		1: "DELETE_TASK",
		2: "KEEPALIVE",
	}
	TaskCommand_CommandType_value = map[string]int32{
		"CREATE_TASK": 0,
		"DELETE_TASK": 1,
		"KEEPALIVE":   2,
	}
)

func (x TaskCommand_CommandType) Enum() *TaskCommand_CommandType {
	p := new(TaskCommand_CommandType)
	*p = x
	return p
}

func (x TaskCommand_CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskCommand_CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_robot_manager_proto_enumTypes[0].Descriptor()
}

func (TaskCommand_CommandType) Type() protoreflect.EnumType {
	return &file_api_grpc_robot_manager_proto_enumTypes[0]
}

func (x TaskCommand_CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskCommand_CommandType.Descriptor instead.
func (TaskCommand_CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{6, 0}
}

type TaskEvent_EventType int32

const (
	TaskEvent_ACK       TaskEvent_EventType = 0 // 确认收到指令
	TaskEvent_PUBLISHED TaskEvent_EventType = 1 // 已发布到 MQTT
	TaskEvent_ERROR     TaskEvent_EventType = 2 // 处理失败
	TaskEvent_KEEPALIVE TaskEvent_EventType = 3 // 保持连接
)

// Enum value maps for TaskEvent_EventType.
var (
	TaskEvent_EventType_name = map[int32]string{
		0: "ACK",
		1: "PUBLISHED",
		2: "ERROR",
		3: "KEEPALIVE",
	}
	TaskEvent_EventType_value = map[string]int32{
		"ACK":       0,
		"PUBLISHED": 1,
		"ERROR":     2,
		"KEEPALIVE": 3,
	}
)

func (x TaskEvent_EventType) Enum() *TaskEvent_EventType {
	p := new(TaskEvent_EventType)
	*p = x
	return p
}

func (x TaskEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_robot_manager_proto_enumTypes[1].Descriptor()
}

func (TaskEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_grpc_robot_manager_proto_enumTypes[1]
}

func (x TaskEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEvent_EventType.Descriptor instead.
func (TaskEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{7, 0}
}

type RegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RobotId        string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeviceInfo     *DeviceInfo            `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`               // 简化的设备信息
	DeviceInfoJson string                 `protobuf:"bytes,4,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"` // 完整的设备信息（JSON格式）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RegistrationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegistrationRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *RegistrationRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RobotId        string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Token          string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeviceInfo     *DeviceInfo            `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`               // 简化的设备信息
	DeviceInfoJson string                 `protobuf:"bytes,4,opt,name=device_info_json,json=deviceInfoJson,proto3" json:"device_info_json,omitempty"` // 完整的设备信息（JSON格式）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetDeviceInfo() *DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *HeartbeatRequest) GetDeviceInfoJson() string {
	if x != nil {
		return x.DeviceInfoJson
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TaskStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUid       string                 `protobuf:"bytes,1,opt,name=task_uid,json=taskUid,proto3" json:"task_uid,omitempty"`
	RobotName     string                 `protobuf:"bytes,2,opt,name=robot_name,json=robotName,proto3" json:"robot_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // pending, running, completed, failed, dead
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Event         string                 `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`                           // Assigned, Downloading, Starting, Started, Completed, Failed
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusRequest) Reset() {
	*x = TaskStatusRequest{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusRequest) ProtoMessage() {}

func (x *TaskStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusRequest.ProtoReflect.Descriptor instead.
func (*TaskStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{4}
}

func (x *TaskStatusRequest) GetTaskUid() string {
	if x != nil {
		return x.TaskUid
	}
	return ""
}

func (x *TaskStatusRequest) GetRobotName() string {
	if x != nil {
		return x.RobotName
	}
	return ""
}

func (x *TaskStatusRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TaskStatusRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TaskStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskStatusRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TaskStatusRequest) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type TaskStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatusResponse) Reset() {
	*x = TaskStatusResponse{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatusResponse) ProtoMessage() {}

func (x *TaskStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatusResponse.ProtoReflect.Descriptor instead.
func (*TaskStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{5}
}

func (x *TaskStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// TaskCommand Manager → Server 的指令
type TaskCommand struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Type          TaskCommand_CommandType `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.TaskCommand_CommandType" json:"type,omitempty"`
	Task          *Task                   `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`                      // type=CREATE_TASK 时有效
	TaskUid       string                  `protobuf:"bytes,3,opt,name=task_uid,json=taskUid,proto3" json:"task_uid,omitempty"` // type=DELETE_TASK 时有效
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCommand) Reset() {
	*x = TaskCommand{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCommand) ProtoMessage() {}

func (x *TaskCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCommand.ProtoReflect.Descriptor instead.
func (*TaskCommand) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{6}
}

func (x *TaskCommand) GetType() TaskCommand_CommandType {
	if x != nil {
		return x.Type
	}
	return TaskCommand_CREATE_TASK
}

func (x *TaskCommand) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *TaskCommand) GetTaskUid() string {
	if x != nil {
		return x.TaskUid
	}
	return ""
}

// TaskEvent Server → Manager 的事件（确认收到）
type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TaskEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=grpc.TaskEvent_EventType" json:"type,omitempty"`
	TaskUid       string                 `protobuf:"bytes,2,opt,name=task_uid,json=taskUid,proto3" json:"task_uid,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{7}
}

func (x *TaskEvent) GetType() TaskEvent_EventType {
	if x != nil {
		return x.Type
	}
	return TaskEvent_ACK
}

func (x *TaskEvent) GetTaskUid() string {
	if x != nil {
		return x.TaskUid
	}
	return ""
}

func (x *TaskEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Task 完整的任务信息
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata
	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Spec
	JobName     string            `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	TargetRobot string            `protobuf:"bytes,5,opt,name=target_robot,json=targetRobot,proto3" json:"target_robot,omitempty"`
	Driver      string            `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	Config      string            `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`                               // JSON 字符串
	Timeout     int64             `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`                            // 秒
	KillTimeout int64             `protobuf:"varint,9,opt,name=kill_timeout,json=killTimeout,proto3" json:"kill_timeout,omitempty"` // 秒
	Env         map[string]string `protobuf:"bytes,10,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Status
	State         string `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"` // pending, dispatching, running, completed, failed
	Message       string `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Task) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *Task) GetTargetRobot() string {
	if x != nil {
		return x.TargetRobot
	}
	return ""
}

func (x *Task) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Task) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Task) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Task) GetKillTimeout() int64 {
	if x != nil {
		return x.KillTimeout
	}
	return 0
}

func (x *Task) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Task) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Task) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	NumCpus       int32                  `protobuf:"varint,4,opt,name=num_cpus,json=numCpus,proto3" json:"num_cpus,omitempty"`
	TotalMemory   int64                  `protobuf:"varint,5,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
	KernelVersion string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_api_grpc_robot_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_robot_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_grpc_robot_manager_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DeviceInfo) GetNumCpus() int32 {
	if x != nil {
		return x.NumCpus
	}
	return 0
}

func (x *DeviceInfo) GetTotalMemory() int64 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

func (x *DeviceInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *DeviceInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_api_grpc_robot_manager_proto protoreflect.FileDescriptor

const file_api_grpc_robot_manager_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/robot_manager.proto\x12\x04grpc\"\xa3\x01\n" +
	"\x13RegistrationRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x121\n" +
	"\vdevice_info\x18\x03 \x01(\v2\x10.grpc.DeviceInfoR\n" +
	"deviceInfo\x12(\n" +
	"\x10device_info_json\x18\x04 \x01(\tR\x0edeviceInfoJson\"J\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa0\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x121\n" +
	"\vdevice_info\x18\x03 \x01(\v2\x10.grpc.DeviceInfoR\n" +
	"deviceInfo\x12(\n" +
	"\x10device_info_json\x18\x04 \x01(\tR\x0edeviceInfoJson\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcf\x01\n" +
	"\x11TaskStatusRequest\x12\x19\n" +
	"\btask_uid\x18\x01 \x01(\tR\ataskUid\x12\x1d\n" +
	"\n" +
	"robot_name\x18\x02 \x01(\tR\trobotName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x14\n" +
	"\x05event\x18\x06 \x01(\tR\x05event\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\"H\n" +
	"\x12TaskStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"\vTaskCommand\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.grpc.TaskCommand.CommandTypeR\x04type\x12\x1e\n" +
	"\x04task\x18\x02 \x01(\v2\n" +
	".grpc.TaskR\x04task\x12\x19\n" +
	"\btask_uid\x18\x03 \x01(\tR\ataskUid\">\n" +
	"\vCommandType\x12\x0f\n" +
	"\vCREATE_TASK\x10\x00\x12\x0f\n" +
	"\vDELETE_TASK\x10\x01\x12\r\n" +
	"\tKEEPALIVE\x10\x02\"\xae\x01\n" +
	"\tTaskEvent\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.grpc.TaskEvent.EventTypeR\x04type\x12\x19\n" +
	"\btask_uid\x18\x02 \x01(\tR\ataskUid\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\tEventType\x12\a\n" +
	"\x03ACK\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\x12\r\n" +
	"\tKEEPALIVE\x10\x03\"\x84\x03\n" +
	"\x04Task\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x19\n" +
	"\bjob_name\x18\x04 \x01(\tR\ajobName\x12!\n" +
	"\ftarget_robot\x18\x05 \x01(\tR\vtargetRobot\x12\x16\n" +
	"\x06driver\x18\x06 \x01(\tR\x06driver\x12\x16\n" +
	"\x06config\x18\a \x01(\tR\x06config\x12\x18\n" +
	"\atimeout\x18\b \x01(\x03R\atimeout\x12!\n" +
	"\fkill_timeout\x18\t \x01(\x03R\vkillTimeout\x12%\n" +
	"\x03env\x18\n" +
	" \x03(\v2\x13.grpc.Task.EnvEntryR\x03env\x12\x14\n" +
	"\x05state\x18\v \x01(\tR\x05state\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x02\n" +
	"\n" +
	"DeviceInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x19\n" +
	"\bnum_cpus\x18\x04 \x01(\x05R\anumCpus\x12!\n" +
	"\ftotal_memory\x18\x05 \x01(\x03R\vtotalMemory\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x124\n" +
	"\x06labels\x18\a \x03(\v2\x1c.grpc.DeviceInfo.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa7\x02\n" +
	"\fRobotManager\x12P\n" +
	"\x17ReportRobotRegistration\x12\x19.grpc.RegistrationRequest\x1a\x1a.grpc.RegistrationResponse\x12G\n" +
	"\x14ReportRobotHeartbeat\x12\x16.grpc.HeartbeatRequest\x1a\x17.grpc.HeartbeatResponse\x12E\n" +
	"\x10ReportTaskStatus\x12\x17.grpc.TaskStatusRequest\x1a\x18.grpc.TaskStatusResponse\x125\n" +
	"\vStreamTasks\x12\x0f.grpc.TaskEvent\x1a\x11.grpc.TaskCommand(\x010\x01B!Z\x1fgithub.com/hxndg/k8s4r/api/grpcb\x06proto3"

var (
	file_api_grpc_robot_manager_proto_rawDescOnce sync.Once
	file_api_grpc_robot_manager_proto_rawDescData []byte
)

func file_api_grpc_robot_manager_proto_rawDescGZIP() []byte {
	file_api_grpc_robot_manager_proto_rawDescOnce.Do(func() {
		file_api_grpc_robot_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_robot_manager_proto_rawDesc), len(file_api_grpc_robot_manager_proto_rawDesc)))
	})
	return file_api_grpc_robot_manager_proto_rawDescData
}

var file_api_grpc_robot_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_grpc_robot_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_grpc_robot_manager_proto_goTypes = []any{
	(TaskCommand_CommandType)(0), // 0: grpc.TaskCommand.CommandType
	(TaskEvent_EventType)(0),     // 1: grpc.TaskEvent.EventType
	(*RegistrationRequest)(nil),  // 2: grpc.RegistrationRequest
	(*RegistrationResponse)(nil), // 3: grpc.RegistrationResponse
	(*HeartbeatRequest)(nil),     // 4: grpc.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 5: grpc.HeartbeatResponse
	(*TaskStatusRequest)(nil),    // 6: grpc.TaskStatusRequest
	(*TaskStatusResponse)(nil),   // 7: grpc.TaskStatusResponse
	(*TaskCommand)(nil),          // 8: grpc.TaskCommand
	(*TaskEvent)(nil),            // 9: grpc.TaskEvent
	(*Task)(nil),                 // 10: grpc.Task
	(*DeviceInfo)(nil),           // 11: grpc.DeviceInfo
	nil,                          // 12: grpc.Task.EnvEntry
	nil,                          // 13: grpc.DeviceInfo.LabelsEntry
}
var file_api_grpc_robot_manager_proto_depIdxs = []int32{
	11, // 0: grpc.RegistrationRequest.device_info:type_name -> grpc.DeviceInfo
	11, // 1: grpc.HeartbeatRequest.device_info:type_name -> grpc.DeviceInfo
	0,  // 2: grpc.TaskCommand.type:type_name -> grpc.TaskCommand.CommandType
	10, // 3: grpc.TaskCommand.task:type_name -> grpc.Task
	1,  // 4: grpc.TaskEvent.type:type_name -> grpc.TaskEvent.EventType
	12, // 5: grpc.Task.env:type_name -> grpc.Task.EnvEntry
	13, // 6: grpc.DeviceInfo.labels:type_name -> grpc.DeviceInfo.LabelsEntry
	2,  // 7: grpc.RobotManager.ReportRobotRegistration:input_type -> grpc.RegistrationRequest
	4,  // 8: grpc.RobotManager.ReportRobotHeartbeat:input_type -> grpc.HeartbeatRequest
	6,  // 9: grpc.RobotManager.ReportTaskStatus:input_type -> grpc.TaskStatusRequest
	9,  // 10: grpc.RobotManager.StreamTasks:input_type -> grpc.TaskEvent
	3,  // 11: grpc.RobotManager.ReportRobotRegistration:output_type -> grpc.RegistrationResponse
	5,  // 12: grpc.RobotManager.ReportRobotHeartbeat:output_type -> grpc.HeartbeatResponse
	7,  // 13: grpc.RobotManager.ReportTaskStatus:output_type -> grpc.TaskStatusResponse
	8,  // 14: grpc.RobotManager.StreamTasks:output_type -> grpc.TaskCommand
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_grpc_robot_manager_proto_init() }
func file_api_grpc_robot_manager_proto_init() {
	if File_api_grpc_robot_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_robot_manager_proto_rawDesc), len(file_api_grpc_robot_manager_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_robot_manager_proto_goTypes,
		DependencyIndexes: file_api_grpc_robot_manager_proto_depIdxs,
		EnumInfos:         file_api_grpc_robot_manager_proto_enumTypes,
		MessageInfos:      file_api_grpc_robot_manager_proto_msgTypes,
	}.Build()
	File_api_grpc_robot_manager_proto = out.File
	file_api_grpc_robot_manager_proto_goTypes = nil
	file_api_grpc_robot_manager_proto_depIdxs = nil
}
